update api/articles to accept sort, order and topic queries
Paul-Ramshaw/news pull request #10
Opened 2022-07-06 15:34 UTC by Paul-Ramshaw

2022-07-06 15:54 UTC, Poonam-raj requested changes
Looking strong - some amendments and suggestions thrown in, have a look and let me know if you have any thoughts. Throw it back when you've amended the testing and the topics (unless you feel strongly the topics validation doesn't need to change)

2022-07-06 15:54 UTC, Poonam-raj commented on models/articles.js
> +  const topicOptions = ['mitch', 'cats', 'paper'];
Love all this validation! Only issue I have with this topicOptions is what if someone added a topic later on? I feel like with all the other columns this isn't likely (we aren't about the change the entire data structure so sort_by wont have this issue). But with topics it's a risk. 

Maybe it means you treat topics differently and only throw errors for it if it is 'not found' rather than as a 'invalid request'

2022-07-06 15:54 UTC, Poonam-raj commented on models/articles.js
> +    whereStr = `WHERE articles.topic = '${topic}'`;
where `GROUP BY` and `ORDER BY` don't allow parameters, we can put parameters into the `WHERE` clause. I'd recommend doing this because it's safer and because I've talked about the above issue with validating topics.

2022-07-06 15:54 UTC, Poonam-raj commented on __tests__/app.test.js
> +      .get('/api/articles?sort_by=invalidorder')
this still says sort_by in the request path

2022-07-06 15:54 UTC, Poonam-raj commented on __tests__/app.test.js
> +  });
What about a test for topics where there are no articles associated but it does exist in our db?

2022-07-07 09:36 UTC, Paul-Ramshaw commented
Made amends, mostly changing the error handling for article topic queries.

2022-07-07 09:58 UTC, Poonam-raj approved these changes
LOVE IT! this is a nice edit on the code, thanks for making the changes :D

2022-07-07 10:01 UTC, merged